project:
  type: book
  output-dir: docs

book:
  chapters:
    - index.qmd
    - about.qmd
    - projects.qmd
    - experience.qmd
    - contact.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

