project:
  type: website
  output-dir: docs
  
editor: visual

format:
  html:
    allow-html: true
    theme: 
      light: zephyr
      dark: darkly 
    css: styles.css
    toc: false
includes:
  in_header: "browser-logo.html" 


website:
  title: "Portfolio"
  favicon: "images/favicon.png"
  navbar:
    style: "light"
    align: center 
    left:
      - href: index.qmd
        text: HOME
      - href: projects.qmd
        text: PROJECTS 
      - href: experience.qmd
        text: WORK EXPERIENCE
      - href: contact.qmd
        text: CONTACT
        


  page-footer:
    left: "© 2025 Fiorella Guillen"
    right:
      - icon: github
        href: https://github.com/fiorellaguillen
      - icon: linkedin
        href: https://www.linkedin.com/in/fiorellaguillenh/
