project:
  type: book
  output-dir: docs

book:
  title: "portfolio"
  author: "Fiorella Guillen Hurtado"
  chapters:
    - index.qmd
    - about.qmd
    - skills.qmd
    - projects.qmd
    - experience.qmd
    - awards.qmd
    - contact.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

